info:
  contact: {}
paths:
  /dashboard:
    get:
      consumes:
      - application/json
      description: Returns a simple json object for testing
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
        "500":
          description: ok
          schema:
            type: string
      summary: Get a single dashboard
      tags:
      - dashboard
    post:
      consumes:
      - application/json
      description: Stores the body dashboard object as a new entry in the database
      produces:
      - application/json
      responses:
        "201":
          description: pong
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "500":
          description: ok
          schema:
            type: string
      summary: Create a new Dashboard
      tags:
      - dashboard
swagger: "2.0"
